# Form implementation generated from reading ui file 'banking.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(719, 571)
        self.entry_AccountName = QtWidgets.QLineEdit(parent=Dialog)
        self.entry_AccountName.setGeometry(QtCore.QRect(10, 10, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.entry_AccountName.setFont(font)
        self.entry_AccountName.setObjectName("entry_AccountName")
        self.button_Account = QtWidgets.QPushButton(parent=Dialog)
        self.button_Account.setGeometry(QtCore.QRect(10, 60, 91, 41))
        self.button_Account.setObjectName("button_Account")
        self.button_SavingAccount = QtWidgets.QPushButton(parent=Dialog)
        self.button_SavingAccount.setGeometry(QtCore.QRect(100, 60, 91, 41))
        self.button_SavingAccount.setObjectName("button_SavingAccount")
        self.comboBox = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox.setGeometry(QtCore.QRect(210, 10, 201, 41))
        self.comboBox.setObjectName("comboBox")
        self.label_AccountInformation = QtWidgets.QLabel(parent=Dialog)
        self.label_AccountInformation.setGeometry(QtCore.QRect(430, 10, 271, 181))
        self.label_AccountInformation.setObjectName("label_AccountInformation")
        self.button_Withdraw = QtWidgets.QPushButton(parent=Dialog)
        self.button_Withdraw.setGeometry(QtCore.QRect(430, 210, 81, 31))
        self.button_Withdraw.setObjectName("button_Withdraw")
        self.entry_Withdraw = QtWidgets.QLineEdit(parent=Dialog)
        self.entry_Withdraw.setGeometry(QtCore.QRect(520, 210, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.entry_Withdraw.setFont(font)
        self.entry_Withdraw.setObjectName("entry_Withdraw")
        self.button_Deposite = QtWidgets.QPushButton(parent=Dialog)
        self.button_Deposite.setGeometry(QtCore.QRect(430, 250, 81, 31))
        self.button_Deposite.setObjectName("button_Deposite")
        self.entry_Deposit = QtWidgets.QLineEdit(parent=Dialog)
        self.entry_Deposit.setGeometry(QtCore.QRect(520, 250, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.entry_Deposit.setFont(font)
        self.entry_Deposit.setObjectName("entry_Deposit")
        self.button_SetBalance = QtWidgets.QPushButton(parent=Dialog)
        self.button_SetBalance.setGeometry(QtCore.QRect(430, 290, 81, 31))
        self.button_SetBalance.setObjectName("button_SetBalance")
        self.entry_SetBalance = QtWidgets.QLineEdit(parent=Dialog)
        self.entry_SetBalance.setGeometry(QtCore.QRect(520, 290, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.entry_SetBalance.setFont(font)
        self.entry_SetBalance.setObjectName("entry_SetBalance")
        self.button_SetName = QtWidgets.QPushButton(parent=Dialog)
        self.button_SetName.setGeometry(QtCore.QRect(430, 330, 81, 31))
        self.button_SetName.setObjectName("button_SetName")
        self.entry_SetName = QtWidgets.QLineEdit(parent=Dialog)
        self.entry_SetName.setGeometry(QtCore.QRect(520, 330, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.entry_SetName.setFont(font)
        self.entry_SetName.setObjectName("entry_SetName")
        self.button_Confirm = QtWidgets.QPushButton(parent=Dialog)
        self.button_Confirm.setGeometry(QtCore.QRect(430, 370, 81, 31))
        self.button_Confirm.setObjectName("button_Confirm")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.entry_AccountName.setText(_translate("Dialog", "Enter account name"))
        self.button_Account.setText(_translate("Dialog", "Account"))
        self.button_SavingAccount.setText(_translate("Dialog", "Saving Account"))
        self.label_AccountInformation.setText(_translate("Dialog", "TextLabel"))
        self.button_Withdraw.setText(_translate("Dialog", "Withdraw"))
        self.entry_Withdraw.setText(_translate("Dialog", "Withdraw Amount"))
        self.button_Deposite.setText(_translate("Dialog", "Deposite"))
        self.entry_Deposit.setText(_translate("Dialog", "Deposite Amount"))
        self.button_SetBalance.setText(_translate("Dialog", "Set Balance"))
        self.entry_SetBalance.setText(_translate("Dialog", "Balance Amount"))
        self.button_SetName.setText(_translate("Dialog", "Set Name"))
        self.entry_SetName.setText(_translate("Dialog", "New Name"))
        self.button_Confirm.setText(_translate("Dialog", "Confirm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
